name: CI

on:
    release
        types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: GitHub Action for IFTTT
      uses: screendriver/ifttt-action@v1.0.0
      with:
        event: ${{secrets.IFTTT_EVENT}}
        key: ${{secrets.IFTTT_KEY}}
