name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Luwangel GitHub Action for IFTTT
          uses: Luwangel/my-ifttt-action@v0.1.1
          with:
            event: ${{secrets.IFTTT_EVENT}}
            key: ${{secrets.IFTTT_KEY}}
